//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.02 at 12:42:55 PM MSK 
//


package ru.johnnygomezzz.soap.products;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="productEntity" type="{http://www.johnnygomezzz.ru/products}productEntity"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "productEntity"
})
@XmlRootElement(name = "getProductByIdResponse")
public class GetProductByIdResponse {

    @XmlElement(required = true)
    protected ProductEntity productEntity;

    /**
     * Gets the value of the productEntity property.
     * 
     * @return
     *     possible object is
     *     {@link ProductEntity }
     *     
     */
    public ProductEntity getProductEntity() {
        return productEntity;
    }

    /**
     * Sets the value of the productEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductEntity }
     *     
     */
    public void setProductEntity(ProductEntity value) {
        this.productEntity = value;
    }

}
